[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.80.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security-Report-Only = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = '''
      default-src 'self';
      connect-src 'self' www.google-analytics.com www.netlifystatus.com;
      font-src cdnjs.cloudflare.com fonts.gstatic.com;
      frame-src www.google.com disqus.com;
      img-src 'self' data: maps.googleapis.com maps.gstatic.com a.tile.openstreetmap.org b.tile.openstreetmap.org c.tile.openstreetmap.org cdnjs.cloudflare.com www.google-analytics.com wowchemy.com raw.githubusercontent.com; 
      manifest-src 'self'; 
      script-src-attr 'unsafe-inline'; 
      script-src-elem 'self' 'unsafe-inline' cdnjs.cloudflare.com identity.netlify.com maps.googleapis.com www.googletagmanager.com; 
      script-src 'unsafe-eval'; 
      style-src-attr 'unsafe-inline'; 
      style-src-elem 'self' 'unsafe-inline' cdnjs.cloudflare.com fonts.googleapis.com
      prefetch-src 'self'; 
      form-action 'none'; 
      frame-ancestors 'none';
      object-src 'none';
      base-uri 'none';
      upgrade-insecure-requests;
      report-uri https://remitheriault.report-uri.com/r/d/csp/reportOnly
      report-to default'''
    Report-To: {"group":"default","max_age":31536000,"endpoints":[{"url":"https://remitheriault.report-uri.com/a/d/g"}],"include_subdomains":true}
    NEL: {"report_to":"default","max_age":31536000,"include_subdomains":true}

[[redirects]]
  from = "/PratiquesPP_2020"
  to = "/PratiquesPP_2020.pdf"
  status = 301
  force = false

[[redirects]]
  from = "/Theriault_CPPA_2018"
  to = "/Theriault_CPPA_2018.pdf"
  status = 301
  force = false

[[redirects]]
  from = "/Theriault_Douglas_2017"
  to = "/Theriault_Douglas_2017.pdf"
  status = 301
  force = false

[[redirects]]
  from = "/Theriault_et_al_2020_QJEP_PREPRINT"
  to = "/Theriault_et_al_2020_QJEP_PREPRINT.pdf"
  status = 301
  force = false

[[redirects]]
  from = "/Theriault_et_al_2020b_QJEP_PREPRINT"
  to = "/Theriault_et_al_2020b_QJEP_PREPRINT.pdf"
  status = 301
  force = false

[[redirects]]
  from = "/Theriault_IPPA_2019"
  to = "/Theriault_IPPA_2019.pdf"
  status = 301
  force = false

[[redirects]]
  from = "/Theriault_ISH_2018"
  to = "/Theriault_ISH_2018.pdf"
  status = 301
  force = false

[[redirects]]
  from = "/Theriault_Mind&Life_2019"
  to = "/Theriault_Mind&Life_2019.pdf"
  status = 301
  force = false

[[redirects]]
  from = "/cv"
  to = "/cv.pdf"
  status = 301
  force = false