baseURL = "http://example.org/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "Yacine Bouaouni's blog"

# Change the default theme to be use when building the site with Hugo
theme = "FeelIt"

[params]
  version = "1.0.X"
  # site description
  description = "Yacine Bouaouni's blog"
  # site keywords
  keywords = ["Theme", "Hugo", "Yacine Bouaouni"]
  # site default theme ("light", "dark", "auto")
  defaultTheme = "auto"
  # public git repo url only then enableGitInfo is true
  gitRepo = ""
  
  dateFormat = "2006-01-02"
  # website images for Open Graph and Twitter Cards
  images = ["/logo.png"]

  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "Yacine Bouaouni"
    # whether to omit favicon resource links
    noFavicon = true
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = "favicon.ico"
    # Android browser theme color
    themeColor = "#ffc40d"
    # Safari mask icon color
    iconColor = "#5bbad5"
    # Windows v8-10 tile color
    tileColor = "#da532c"
  
  [params.about]
    # whether to enable profile on about page
    # depends on .Site.Params.home.profile.enable
    enable = false
    # whether to enable param layout
    param = false
    # title for param layout
    paramTitle = "Personal Information"
    # general description of your site
    # can be write with markdown style
    description = ""
    [[params.about.status]]
      faIcon = "fas fa-university"
      title = "University"
      desc = "ENS Paris Saclay"
    [[params.about.status]]
      title = "Location"
      faIcon = "fas fa-map-marker-alt"
      desc = "Paris, France"
    # description of your parameter
    #[[params.about.parameter]]
    #  language = "UI/UX"
    #  level = "80"
    #[[params.about.parameter]]
    #  language = "HTML"
    #  level = "70"
    #[[params.about.parameter]]
    #  language = "Go"
    #  level = "60"
  [params.home]
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      avatarURL = "/images/me.jpg"
      itle = ""
      # subtitle shown in home page
      subtitle = "Hello AI aficionados, Welcome to my Blog!"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true

      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
      imagePreview = true
      defaultHiddenFromHomePage = false

  [params.oembed]
    # Privacy config (https://gohugo.io/about/hugo-and-gdpr/)
    privacy = false
    [params.oembed.facebook]
      # Facebook Aplication Identity and Client Token (<APPID>|<CLIENTTOKEN>)
      accessToken = ""
    [params.oembed.twitter]
      enableDNT = false


  [params.social]
    GitHub = "yacinebouaouni"
    Linkedin = "yacine-bouaouni-4b0698175"
    Twitter = ""
    Instagram = ""
    Facebook = ""
    Telegram = ""
    Medium = "@yacinebouaouni07"
    Gitlab = ""
    Youtubelegacy = ""
    Youtubecustom = ""
    Youtubechannel = ""
    Tumblr = ""
    Quora = ""
    Keybase = ""
    Pinterest = ""
    Reddit = ""
    Codepen = ""
    FreeCodeCamp = ""
    Bitbucket = ""
    Stackoverflow = ""
    Weibo = ""
    Odnoklassniki = ""
    VK = ""
    Flickr = ""
    Xing = ""
    Snapchat = ""
    Soundcloud = ""
    Spotify = ""
    Bandcamp = ""
    Paypal = ""
    Fivehundredpx = ""
    Mix = ""
    Goodreads = ""
    Lastfm = ""
    Foursquare = ""
    Hackernews = ""
    Kickstarter = ""
    Patreon = ""
    Steam = ""
    Twitch = ""
    Strava = ""
    Skype = ""
    Whatsapp = ""
    Zhihu = ""
    Douban = ""
    Angellist = ""
    Slidershare = ""
    Jsfiddle = ""
    Deviantart = ""
    Behance = ""
    Dribbble = ""
    Wordpress = ""
    Vine = ""
    Googlescholar = ""
    Researchgate = "Yacine-Bouaouni"
    Mastodon = ""
    Thingiverse = ""
    Devto = ""
    Gitea = ""
    XMPP = ""
    Matrix = ""
    Bilibili = ""
    Email = "yacinebouaouni1998@gmail.com"
    Resume = ""
  
  [params.page]
    hiddenFromHomePage = false
    hiddenFromSearch = false
    twemoji = false
    lightgallery = false
    ruby = true
    fraction = true
    fontawesome = true
    cdnfontawesome = true
    linkToMarkdown = true
    improveArticle = ""
    rssFullText = false
    [params.page.toc]
      enable = true
      keepStatic = true
      auto = true

  [params.page.math]
      enable = true
      # default block delimiter is $$ ... $$ and \\[ ... \\]
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # default inline delimiter is $ ... $ and \\( ... \\)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # KaTeX extension copy_tex
      copyTex = true
      # KaTeX extension mhchem
      mhchem = true
  
  [params.page.code]
      # whether to show the copy button of the code block
      copy = true
      # the maximum number of lines of displayed code by default
      maxShownLines = 10
  
  [params.page.mapbox]
      # access token of Mapbox GL JS
      accessToken = ""
      # style for the light theme
      lightStyle = "mapbox://styles/mapbox/light-v9"
      # style for the dark theme
      darkStyle = "mapbox://styles/mapbox/dark-v9"
      # whether to add NavigationControl
      navigation = true
      # whether to add GeolocateControl
      geolocate = true
      # whether to add ScaleControl
      scale = true
      # whether to add FullscreenControl
      fullscreen = true
  
  [params.page.share]
      enable = true
      Twitter = false
      Facebook = false
      Linkedin = true
      Whatsapp = true
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = false
      Instapaper = false
      Pocket = false
      Digg = false
      Stumbleupon = false
      Flipboard = false
      Weibo = false
      Renren = false
      Myspace = false
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Mix = false

  [params.page.comment]
      enable = true
      # Disqus comment config
      [params.page.comment.disqus]
        enable = false
        # Disqus shortname to use Disqus in posts
        shortname = ""
      # Vssue comment config (https://github.com/meteorlxy/vssue)
      [params.page.comment.vssue]
        enable = false
        # Vssue platform API ("bitbucket", "gitea", "gitee", "github", "github-v4", "gitlab")
        platform = ""
        owner = ""
        repo = ""
        clientId = ""
        clientSecret = ""
      # Gitalk comment config
      [params.page.comment.gitalk]
        enable = false
        owner = ""
        repo = ""
        clientId = ""
        clientSecret = ""
      # Valine comment config
      [params.page.comment.valine]
        enable = false
        appId = ""
        appKey = ""
        placeholder = ""
        avatar = "mp"
        meta= ""
        pageSize = 10
        lang = ""
        visitor = true
        recordIP = true
        highlight = true
        enableQQ = false
        serverURLs = ""
    [params.typeit]
      # typing speed between each step (measured in milliseconds)
      speed = 100
      # blinking speed of the cursor (measured in milliseconds)
      cursorSpeed = 1000
      # character used for the cursor (HTML format is supported)
      cursorChar = "|"
      # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
      duration = -1
    [params.verification]
      google = ""
      bing = ""
      yandex = ""
      pinterest = ""
      baidu = ""
    [params.seo]
      # image URL
      image = ""
      # thumbnail URL
      thumbnailUrl = ""    



# Author config
[author]
  name = "Yacine Bouaouni"
  email = "yacinebouaouni1998@gmail.com"
  link = ""

[menu]
  [[menu.main]]
    identifier = "about"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "About"
    url = "/about/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "projects"
    pre = ""
    post = ""
    name = "Projects"
    url = "/projects/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "notes"
    pre = ""
    post = ""
    name = "Notes"
    url = "/Notes/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 4
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 5
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 6


# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration
    # (https://github.com/khusika/FeelIt/issues/158)
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

